import type { OEvent, OUser, OReview, OVenue } from "./types";

export const SEED_VENUES: OVenue[] = [
  { id: "v-bacc", name: "Bangkok Art and Culture Centre", area: "Siam", geoLat: 13.7466, geoLng: 100.5293, type: "institution" },
  { id: "v-moca", name: "Museum of Contemporary Art Bangkok", area: "Lat Phrao", geoLat: 13.8005, geoLng: 100.5745, type: "museum" },
  { id: "v-rcb", name: "River City Bangkok", area: "Charoenkrung", geoLat: 13.7329, geoLng: 100.5145, type: "gallery" },
  { id: "v-w30", name: "Warehouse 30", area: "Charoenkrung", geoLat: 13.7241, geoLng: 100.5101, type: "pop-up" },
  { id: "v-cartel", name: "Cartel Artspace", area: "Ekkamai", geoLat: 13.7182, geoLng: 100.5852, type: "gallery" },
  { id: "v-wtf", name: "WTF Bangkok", area: "Ari", geoLat: 13.7782, geoLng: 100.5351, type: "gallery" },
  { id: "v-sac", name: "SAC Gallery", area: "Silom", geoLat: 13.7277, geoLng: 100.5318, type: "gallery" },
  { id: "v-tcdc", name: "TCDC Bangkok", area: "Charoenkrung", geoLat: 13.7255, geoLng: 100.5148, type: "institution" },
  { id: "v-ver", name: "Gallery VER", area: "Ekkamai", geoLat: 13.7171, geoLng: 100.5828, type: "gallery" },
  { id: "v-jtac", name: "Jim Thompson Art Center", area: "Pathumwan", geoLat: 13.7445, geoLng: 100.5317, type: "institution" },
];

export const SEED_USERS: OUser[] = [
  {
    id: "u-1", handle: "rawiphat_sees", nameTH: "รวิภัทร์", nameEN: "Rawiphat",
    bio: "Art student, KMITL. Probably at an opening right now.", langPref: "th",
    eyeScore: 312, joinedAt: "2026-01-15", isVerified: true,
    attendedCount: 34, reviewCount: 28, interests: ["exhibition", "installation"], avatarColor: "#b6c62a",
  },
  {
    id: "u-2", handle: "nontawat_eye", nameTH: "นนทวัฒน์", nameEN: "Nontawat",
    bio: "Photographer + chronic gallery-hopper. Bangkok and everywhere.", langPref: "en",
    eyeScore: 547, joinedAt: "2026-01-03", isVerified: true,
    attendedCount: 67, reviewCount: 51, interests: ["exhibition", "performance", "festival"], avatarColor: "#7ec5d6",
  },
  {
    id: "u-3", handle: "ploy.bkk", nameTH: "พลอย", nameEN: "Ploy",
    bio: "ชอบงานที่ทำให้งงๆ แต่ในแบบดี", langPref: "th",
    eyeScore: 189, joinedAt: "2026-02-10", isVerified: false,
    attendedCount: 19, reviewCount: 14, interests: ["installation", "performance"], avatarColor: "#ff7b72",
  },
  {
    id: "u-4", handle: "krittin_art", nameTH: "กฤตธิ์", nameEN: "Krittin",
    bio: "Independent curator. Writes for Art4D.", langPref: "both",
    eyeScore: 891, joinedAt: "2026-01-01", isVerified: true,
    attendedCount: 89, reviewCount: 76, interests: ["exhibition", "venue"], avatarColor: "#f0b95f",
  },
  {
    id: "u-5", handle: "mai_watching", nameTH: "ไหม", nameEN: "Mai",
    bio: "Looking for things that make me feel something.", langPref: "th",
    eyeScore: 78, joinedAt: "2026-03-05", isVerified: false,
    attendedCount: 8, reviewCount: 7, interests: ["exhibition"], avatarColor: "#a78bfa",
  },
  {
    id: "u-6", handle: "suporn_lens", nameTH: "สุพรรณ", nameEN: "Suporn",
    bio: "Documentary photographer. Currently angry about gentrification.", langPref: "both",
    eyeScore: 445, joinedAt: "2026-01-22", isVerified: true,
    attendedCount: 43, reviewCount: 38, interests: ["exhibition", "installation"], avatarColor: "#34d399",
  },
  {
    id: "u-7", handle: "kanitta.bk", nameTH: "กณิตา", nameEN: "Kanitta",
    bio: "Textile artist. อยากเห็นงานที่คนไทยทำสำหรับคนไทย", langPref: "th",
    eyeScore: 234, joinedAt: "2026-02-01", isVerified: true,
    attendedCount: 27, reviewCount: 22, interests: ["exhibition", "installation"], avatarColor: "#f472b6",
  },
  {
    id: "u-8", handle: "tara_crit", nameTH: "ทาร่า", nameEN: "Tara",
    bio: "Ex-gallerist. Now just a person who looks at things. More honest that way.", langPref: "en",
    eyeScore: 623, joinedAt: "2026-01-08", isVerified: true,
    attendedCount: 71, reviewCount: 59, interests: ["exhibition", "venue", "festival"], avatarColor: "#60a5fa",
  },
];

// Placeholder gradient image URLs (via Unsplash-style source; using abstract descriptors)
const IMG = (seed: string) => `https://picsum.photos/seed/${seed}/800/600`;

export const SEED_EVENTS: OEvent[] = [
  {
    id: "evt-1",
    type: "exhibition",
    titleTH: "สถาปัตยกรรมผี",
    titleEN: "Ghost Architecture",
    descriptionTH: "นิทรรศการศิลปะจัดวางเฉพาะพื้นที่ที่สำรวจซากอาคารและความทรงจำของกรุงเทพฯ ที่ถูกทำลายไป ศิลปินสามคนตั้งคำถามว่าเราจำอะไรได้ และจำอะไรไม่ได้ผ่านสื่อกลาง ภาพถ่าย เสียง และวัสดุที่พบในพื้นที่",
    descriptionEN: "A site-specific installation inside the old Bangkok General Post Office exploring demolished buildings and erased urban memory. Three artists ask what we choose to remember — and what the city actively forgets — through photography, field recordings, and found architectural fragments.",
    venueId: "v-bacc",
    venueName: "Bangkok Art and Culture Centre",
    venueArea: "Siam",
    startDate: "2026-05-10",
    endDate: "2026-07-06",
    geoLat: 13.7466,
    geoLng: 100.5293,
    coverImage: IMG("ghost-arch-bkk"),
    images: [IMG("ghost-arch-bkk"), IMG("ghost-detail-1"), IMG("ghost-detail-2")],
    organizerId: "u-4",
    isPaid: false,
    tags: ["site-specific", "memory", "urban", "photography"],
    criticAxisRatings: { moved: 4, changedMyMind: 3, cantStopThinking: 5 },
  },
  {
    id: "evt-2",
    type: "exhibition",
    titleTH: "ลิ้นไฟ",
    titleEN: "Tongues of Fire",
    descriptionTH: "จิตรกรรมร่วมสมัยไทยจากศิลปิน 8 คน ที่สำรวจความโกรธ ความศรัทธา และความรุนแรงเชิงสัญลักษณ์ในประเพณีภาพวาดไทย ผลงานที่เผาไหม้ด้วยสี แต่เงียบงันในท่าที",
    descriptionEN: "Eight Thai painters channel rage, devotion, and symbolic violence through the idiom of traditional Thai painting — works that burn with colour but speak in a whisper. Possibly the most divisive show in Bangkok this year.",
    venueId: "v-rcb",
    venueName: "River City Bangkok",
    venueArea: "Charoenkrung",
    startDate: "2026-05-20",
    endDate: "2026-06-29",
    geoLat: 13.7329,
    geoLng: 100.5145,
    coverImage: IMG("tongues-fire-thai"),
    images: [IMG("tongues-fire-thai"), IMG("tongues-fire-2"), IMG("tongues-fire-3")],
    organizerId: "u-4",
    isPaid: false,
    tags: ["painting", "thai-contemporary", "religion", "politics"],
    criticAxisRatings: { moved: 5, overhyped: 2 },
  },
  {
    id: "evt-3",
    type: "exhibition",
    titleTH: "หมายเหตุขอบหน้า",
    titleEN: "Margin Notes",
    descriptionTH: "ภาพถ่ายเชิงสารคดีจากศิลปิน 12 คนจากเอเชียตะวันออกเฉียงใต้ที่บันทึกชีวิตของผู้คนที่ถูกลืม: แรงงานข้ามชาติ คนไร้บ้าน ชุมชนชายขอบ ผลงานที่บอกเล่าเรื่องราวโดยไม่เคยแสร้งทำเป็นว่าตัวเองเป็นกลาง",
    descriptionEN: "Documentary photography from 12 Southeast Asian artists recording lives at the margin: migrant workers, displaced communities, urban homeless. Work that tells stories without pretending to be neutral — and doesn't apologise for that.",
    venueId: "v-w30",
    venueName: "Warehouse 30",
    venueArea: "Charoenkrung",
    startDate: "2026-05-15",
    endDate: "2026-06-28",
    geoLat: 13.7241,
    geoLng: 100.5101,
    coverImage: IMG("margin-notes-sea"),
    images: [IMG("margin-notes-sea"), IMG("margin-2"), IMG("margin-3")],
    organizerId: "u-6",
    isPaid: false,
    tags: ["documentary", "photography", "social", "SEA"],
    criticAxisRatings: { moved: 5, changedMyMind: 4, underrated: 3 },
  },
  {
    id: "evt-4",
    type: "exhibition",
    titleTH: "หลังน้ำท่วม",
    titleEN: "After the Flood",
    descriptionTH: "นิทรรศการสหวิทยาการที่สำรวจวิกฤตน้ำ: น้ำท่วม ภัยแล้ง และความไม่เท่าเทียมด้านน้ำสะอาดในเอเชียตะวันออกเฉียงใต้ ระหว่างวิทยาศาสตร์ นโยบาย และศิลปะ",
    descriptionEN: "An interdisciplinary show at MOCA navigating the water crisis: flooding, drought, and inequitable access to clean water across Southeast Asia. Where science, policy and art collide — and sometimes cancel each other out.",
    venueId: "v-moca",
    venueName: "Museum of Contemporary Art Bangkok",
    venueArea: "Lat Phrao",
    startDate: "2026-04-25",
    endDate: "2026-07-20",
    geoLat: 13.8005,
    geoLng: 100.5745,
    coverImage: IMG("after-flood-moca"),
    images: [IMG("after-flood-moca"), IMG("flood-2"), IMG("flood-3")],
    organizerId: "u-4",
    isPaid: true,
    ticketUrl: "https://mocabangkok.com",
    tags: ["climate", "water", "interdisciplinary", "SEA"],
    criticAxisRatings: { moved: 3, confused: 2, overhyped: 3 },
  },
  {
    id: "evt-5",
    type: "exhibition",
    titleTH: "หม้อข้าวหม้อแกง",
    titleEN: "Same Pot, Different Spoon",
    descriptionTH: "ศิลปะเซรามิกร่วมสมัยที่ตีความใหม่ถึงภาชนะและอาหารในฐานะตัวแทนของอัตลักษณ์ครอบครัว ชาติพันธุ์ และชนชั้น ศิลปิน 6 คนนำเสนอผลงานที่ดูเรียบง่ายแต่เต็มไปด้วยความหมาย",
    descriptionEN: "Six ceramic artists reinterpret vessels and food as stand-ins for family, ethnicity, and class. Work that looks modest and carries a mountain. BACC's quietest show this season — and the one that hits hardest if you give it time.",
    venueId: "v-bacc",
    venueName: "Bangkok Art and Culture Centre",
    venueArea: "Siam",
    startDate: "2026-05-01",
    endDate: "2026-06-30",
    geoLat: 13.7466,
    geoLng: 100.5293,
    coverImage: IMG("ceramics-same-pot"),
    images: [IMG("ceramics-same-pot"), IMG("ceramics-2"), IMG("ceramics-3")],
    organizerId: "u-7",
    isPaid: false,
    tags: ["ceramics", "identity", "family", "craft"],
    criticAxisRatings: { moved: 4, wantToOwn: 5, underrated: 4 },
  },
  {
    id: "evt-6",
    type: "exhibition",
    titleTH: "คนที่มองไม่เห็น",
    titleEN: "The Invisible Workers",
    descriptionTH: "ภาพถ่ายสารคดีว่าด้วยแรงงานที่มองไม่เห็น: คนทำความสะอาด พนักงานส่งของ คนขายของริมถนน ที่ทำให้กรุงเทพฯ ทำงานอยู่ได้ทุกวัน แต่ถูกทำให้หายไปจากภาพลักษณ์ของเมือง",
    descriptionEN: "Documentary photography on Bangkok's unseen workforce: cleaners, delivery workers, street vendors who make the city run but who the city's image-makers pretend do not exist. Shot over three years. Hard to look at. Harder to look away.",
    venueId: "v-cartel",
    venueName: "Cartel Artspace",
    venueArea: "Ekkamai",
    startDate: "2026-05-25",
    endDate: "2026-06-21",
    geoLat: 13.7182,
    geoLng: 100.5852,
    coverImage: IMG("invisible-workers-bkk"),
    images: [IMG("invisible-workers-bkk"), IMG("workers-2"), IMG("workers-3")],
    organizerId: "u-6",
    isPaid: false,
    tags: ["photography", "labor", "urban", "social"],
    criticAxisRatings: { moved: 5, cantStopThinking: 4 },
  },
  {
    id: "evt-7",
    type: "installation",
    titleTH: "นีออนสังสารวัฏ",
    titleEN: "NEON SAMSARA",
    descriptionTH: "อิมเมอร์ซีฟอาร์ตในอดีตพื้นที่ค้าปลีก: ห้องแห่งแสงนีออน เสียง และข้อมูลดิจิทัลที่สำรวจวัฏจักรของการบริโภค การเกิด และการตาย ทั้งดูดีในรูปและมีอะไรมากกว่านั้น (อาจ)",
    descriptionEN: "Immersive installation in a former Samyan retail space: rooms of neon light, generative sound, and looping data visualizations exploring the cycle of consumption, birth, and death. Looks amazing on your phone. May or may not mean anything. The room will decide.",
    venueId: "v-tcdc",
    venueName: "TCDC Bangkok",
    venueArea: "Charoenkrung",
    startDate: "2026-05-01",
    endDate: "2026-07-31",
    geoLat: 13.7255,
    geoLng: 100.5148,
    coverImage: IMG("neon-samsara-bkk"),
    images: [IMG("neon-samsara-bkk"), IMG("neon-2"), IMG("neon-3")],
    organizerId: "u-4",
    isPaid: true,
    ticketUrl: "https://tcdc.or.th",
    tags: ["immersive", "digital", "installation", "neon"],
    criticAxisRatings: { confused: 3, overhyped: 4, cantStopThinking: 2 },
  },
  {
    id: "evt-8",
    type: "exhibition",
    titleTH: "ความทรงจำคอนกรีต",
    titleEN: "Concrete Memory",
    descriptionTH: "ภาพถ่ายอุตสาหกรรมจากคลังสินค้า โรงงาน และพื้นที่ที่กำลังถูกรื้อถอนรอบกรุงเทพฯ บันทึกพื้นที่ที่กำลังจะหายไปก่อนที่ทุนใหม่จะมาแทนที่",
    descriptionEN: "Industrial photography across Bangkok's warehouses, factories, and demolition sites — recording what capital is in the process of erasing. A document, not a lament. Shot on film.",
    venueId: "v-w30",
    venueName: "Warehouse 30",
    venueArea: "Charoenkrung",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    geoLat: 13.7241,
    geoLng: 100.5101,
    coverImage: IMG("concrete-memory-bkk"),
    images: [IMG("concrete-memory-bkk"), IMG("concrete-2"), IMG("concrete-3")],
    organizerId: "u-6",
    isPaid: false,
    tags: ["photography", "industrial", "film", "urban"],
  },
  {
    id: "evt-9",
    type: "performance",
    titleTH: "เครื่องบูชา",
    titleEN: "Offerings",
    descriptionTH: "ชุดการแสดงสดสัปดาห์ละครั้ง ที่ผสมพิธีกรรม การเคลื่อนไหว และเสียง ศิลปินนำเสนอคำถามเกี่ยวกับร่างกาย อำนาจ และสิ่งศักดิ์สิทธิ์ในยุคดิจิทัล บางคืนไม่มีอะไรเกิดขึ้น บางคืนเปลี่ยนทุกอย่าง",
    descriptionEN: "A weekly performance series at WTF mixing ritual, movement and sound. Artists ask questions about body, power, and the sacred in the digital age. Some nights nothing happens. Some nights everything does. You won't know which until you're there.",
    venueId: "v-wtf",
    venueName: "WTF Bangkok",
    venueArea: "Ari",
    startDate: "2026-05-01",
    endDate: "2026-07-25",
    geoLat: 13.7782,
    geoLng: 100.5351,
    coverImage: IMG("offerings-performance-bkk"),
    images: [IMG("offerings-performance-bkk"), IMG("offerings-2")],
    organizerId: "u-3",
    isPaid: false,
    tags: ["performance", "ritual", "live", "body"],
  },
  {
    id: "evt-10",
    type: "exhibition",
    titleTH: "เธอผู้โค้งงอแสง",
    titleEN: "She Who Bends Light",
    descriptionTH: "ประติมากรรมจากศิลปินหญิงและ non-binary 7 คน ที่สำรวจความสัมพันธ์ระหว่างร่างกาย พื้นที่ และแสง ผลงานที่ฉีกทิ้งความเรียบร้อยเพื่อหาพื้นที่ใหม่",
    descriptionEN: "Sculpture from seven women and non-binary artists exploring the relationship between body, space, and light. Work that tears up politeness to find something larger. SAC's best group show in two years.",
    venueId: "v-sac",
    venueName: "SAC Gallery",
    venueArea: "Silom",
    startDate: "2026-05-18",
    endDate: "2026-06-29",
    geoLat: 13.7277,
    geoLng: 100.5318,
    coverImage: IMG("she-bends-light-sac"),
    images: [IMG("she-bends-light-sac"), IMG("she-2"), IMG("she-3")],
    organizerId: "u-4",
    isPaid: false,
    tags: ["sculpture", "women", "light", "body"],
    criticAxisRatings: { moved: 5, wantToOwn: 3, changedMyMind: 4 },
  },
  {
    id: "evt-11",
    type: "exhibition",
    titleTH: "ผิวข้อมูล",
    titleEN: "Data Skins",
    descriptionTH: "ศิลปะสื่อใหม่ที่สำรวจขอบเขตระหว่างร่างกายมนุษย์และข้อมูลดิจิทัล ผลงานบางชิ้นสร้างขึ้นโดยใช้ข้อมูลชีวภาพของผู้ชมเอง คำถาม: ข้อมูลของคุณเป็นคุณหรือเปล่า",
    descriptionEN: "New media work at TCDC exploring where the human body ends and data begins. Some pieces are generated from visitors' own biometric data collected at the door. The work asks: is your data you? Disquieting answer: maybe.",
    venueId: "v-tcdc",
    venueName: "TCDC Bangkok",
    venueArea: "Charoenkrung",
    startDate: "2026-04-15",
    endDate: "2026-06-15",
    geoLat: 13.7255,
    geoLng: 100.5148,
    coverImage: IMG("data-skins-tcdc"),
    images: [IMG("data-skins-tcdc"), IMG("data-2"), IMG("data-3")],
    organizerId: "u-4",
    isPaid: false,
    tags: ["new-media", "biotech", "data", "body"],
    criticAxisRatings: { confused: 4, cantStopThinking: 5, overhyped: 2 },
  },
  {
    id: "evt-12",
    type: "exhibition",
    titleTH: "ขุดขึ้นมา",
    titleEN: "Unburied",
    descriptionTH: "นิทรรศการผสมสื่อเกี่ยวกับประวัติศาสตร์ที่ถูกฝัง: เหตุการณ์ทางการเมืองที่ถูกลบออกจากการศึกษาไทย ศิลปินใช้เอกสาร ภาพถ่ายเก่า และงานศิลปะเพื่อขุดค้นความทรงจำที่ถูกห้ามไม่ให้จำ",
    descriptionEN: "Mixed-media exhibition on buried history: political events systematically erased from Thai education. Artists use archival documents, old photographs, and fabricated objects to surface memories that have been officially forgotten. Brave. Possibly illegal depending on who's counting.",
    venueId: "v-bacc",
    venueName: "Bangkok Art and Culture Centre",
    venueArea: "Siam",
    startDate: "2026-05-05",
    endDate: "2026-06-30",
    geoLat: 13.7466,
    geoLng: 100.5293,
    coverImage: IMG("unburied-bacc"),
    images: [IMG("unburied-bacc"), IMG("unburied-2"), IMG("unburied-3")],
    organizerId: "u-4",
    isPaid: false,
    tags: ["history", "politics", "archives", "memory"],
    criticAxisRatings: { moved: 5, changedMyMind: 5, cantStopThinking: 5 },
  },
  {
    id: "evt-13",
    type: "installation",
    titleTH: "ชั่วโมงนุ่ม",
    titleEN: "Soft Hours",
    descriptionTH: "ศิลปะสิ่งทอและเสียงที่สำรวจความทรงจำของผ้าและเวลา ดูช้า รู้สึกช้า บางทีนั่งดูนานเกินไปและพบว่าตัวเองกำลังร้องไห้โดยไม่รู้สาเหตุ",
    descriptionEN: "Textile and sound installation at Gallery VER exploring the memory encoded in fabric and the texture of time. Slow to enter. Slow to leave. Several visitors have reported crying without knowing why. Bring tissues, or don't, and find out.",
    venueId: "v-ver",
    venueName: "Gallery VER",
    venueArea: "Ekkamai",
    startDate: "2026-05-22",
    endDate: "2026-07-05",
    geoLat: 13.7171,
    geoLng: 100.5828,
    coverImage: IMG("soft-hours-ver"),
    images: [IMG("soft-hours-ver"), IMG("soft-2"), IMG("soft-3")],
    organizerId: "u-7",
    isPaid: false,
    tags: ["textile", "sound", "installation", "slow"],
    criticAxisRatings: { moved: 5, cantStopThinking: 4, underrated: 5 },
  },
  {
    id: "evt-14",
    type: "exhibition",
    titleTH: "ดินกลบกาก",
    titleEN: "Night Soil",
    descriptionTH: "ภาพถ่ายที่บันทึกความสัมพันธ์ระหว่างการเกษตรและการขยายตัวของเมืองในไทย: ทุ่งนาที่กลายเป็นหมู่บ้านจัดสรร คนที่ยังปลูกผักในซอกตึก ดินที่รอให้ตึกกด",
    descriptionEN: "Photography at Jim Thompson Art Center on the relationship between agriculture and urban sprawl in Thailand: rice paddies becoming housing estates, people still growing vegetables in building gaps, soil waiting to be paved. About patience, and the end of it.",
    venueId: "v-jtac",
    venueName: "Jim Thompson Art Center",
    venueArea: "Pathumwan",
    startDate: "2026-04-20",
    endDate: "2026-06-22",
    geoLat: 13.7445,
    geoLng: 100.5317,
    coverImage: IMG("night-soil-jtac"),
    images: [IMG("night-soil-jtac"), IMG("night-soil-2"), IMG("night-soil-3")],
    organizerId: "u-6",
    isPaid: false,
    tags: ["photography", "agriculture", "urbanization", "land"],
    criticAxisRatings: { moved: 4, changedMyMind: 4, underrated: 3 },
  },
  {
    id: "evt-15",
    type: "installation",
    titleTH: "คณะกรรมการ",
    titleEN: "The Committee",
    descriptionTH: "งานจัดวางแบบเสียดสีที่สร้างห้องประชุมในจินตนาการซึ่งอำนาจตัดสินใจเกี่ยวกับศิลปะ บันทึกการประชุม นโยบาย และเอกสารสมมติที่สะท้อนถึงการเมืองของการคัดเลือกและการอนุมัติในโลกศิลปะ",
    descriptionEN: "A satirical installation building a fictional committee that decides what counts as art: meeting minutes, selection policies, rejection letters, funding criteria. Cartel's most overtly political show in years. Some establishment figures have reportedly left early. Draw your own conclusions.",
    venueId: "v-cartel",
    venueName: "Cartel Artspace",
    venueArea: "Ekkamai",
    startDate: "2026-05-30",
    endDate: "2026-07-12",
    geoLat: 13.7182,
    geoLng: 100.5852,
    coverImage: IMG("the-committee-cartel"),
    images: [IMG("the-committee-cartel"), IMG("committee-2"), IMG("committee-3")],
    organizerId: "u-4",
    isPaid: false,
    tags: ["installation", "satire", "politics", "art-world"],
    criticAxisRatings: { confused: 3, changedMyMind: 5, cantStopThinking: 4 },
  },
];

export const SEED_REVIEWS: OReview[] = [
  // Ghost Architecture (evt-1) — emotional, divisive
  { id: "r-1", userId: "u-1", targetType: "event", targetId: "evt-1", axisKeys: ["moved", "cantStopThinking"], writtenTakeEN: "The sound of demolition recordings looping in the old post office — I stood there for 20 minutes unable to leave. Bangkok as a haunting.", writtenTakeTH: "เสียงการรื้อถอนที่วนซ้ำในอาคารเก่า — ฉันยืนอยู่นั่นนานมากจนลืมว่าจะไปไหนต่อ", attendanceVerified: true, createdAt: "2026-05-12T14:30:00Z" },
  { id: "r-2", userId: "u-2", targetType: "event", targetId: "evt-1", axisKeys: ["changedMyMind", "moved"], writtenTakeEN: "I've spent years photographing demolitions. This is the first time I felt the work I do might matter.", attendanceVerified: true, createdAt: "2026-05-13T10:15:00Z" },
  { id: "r-3", userId: "u-3", targetType: "event", targetId: "evt-1", axisKeys: ["confused"], writtenTakeTH: "ไม่ค่อยเข้าใจว่าสามศิลปินทำงานร่วมกันยังไง รู้สึกแยกส่วน", attendanceVerified: false, createdAt: "2026-05-14T16:00:00Z" },
  { id: "r-4", userId: "u-4", targetType: "event", targetId: "evt-1", axisKeys: ["moved", "cantStopThinking", "changedMyMind"], writtenTakeEN: "This is what site-specific work should be. The building is the work. The absence is the subject.", attendanceVerified: true, createdAt: "2026-05-11T11:00:00Z" },
  { id: "r-5", userId: "u-5", targetType: "event", targetId: "evt-1", axisKeys: ["overhyped"], writtenTakeTH: "ฟังดูดีกว่าที่เห็น ราวกับว่าแนวคิดสำคัญกว่าผลงานจริง", attendanceVerified: true, createdAt: "2026-05-15T09:30:00Z" },
  { id: "r-6", userId: "u-8", targetType: "event", targetId: "evt-1", axisKeys: ["moved", "wantToOwn"], writtenTakeEN: "The found architectural fragments installed in glass cases. I wanted to steal one. That's the highest compliment I know.", attendanceVerified: true, createdAt: "2026-05-16T15:00:00Z" },

  // Tongues of Fire (evt-2) — highly divisive
  { id: "r-7", userId: "u-1", targetType: "event", targetId: "evt-2", axisKeys: ["moved", "cantStopThinking"], writtenTakeTH: "ภาพวาดที่รู้สึกเหมือนกำลังดูไฟที่กำลังกิน เร้าใจมาก", attendanceVerified: true, createdAt: "2026-05-22T13:00:00Z" },
  { id: "r-8", userId: "u-3", targetType: "event", targetId: "evt-2", axisKeys: ["confused", "overhyped"], writtenTakeTH: "สีสวยมาก แต่ไม่รู้ว่ามันพูดถึงอะไร", attendanceVerified: false, createdAt: "2026-05-23T17:00:00Z" },
  { id: "r-9", userId: "u-4", targetType: "event", targetId: "evt-2", axisKeys: ["moved", "changedMyMind"], writtenTakeEN: "I arrived skeptical about the traditional idiom. I left rethinking everything I know about restraint in painting.", attendanceVerified: true, createdAt: "2026-05-21T14:00:00Z" },
  { id: "r-10", userId: "u-5", targetType: "event", targetId: "evt-2", axisKeys: ["overhyped"], attendanceVerified: false, createdAt: "2026-05-24T10:00:00Z" },
  { id: "r-11", userId: "u-6", targetType: "event", targetId: "evt-2", axisKeys: ["cantStopThinking", "moved"], writtenTakeEN: "The rage is in the technique, not the subject matter. That's what makes it work.", attendanceVerified: true, createdAt: "2026-05-22T18:00:00Z" },
  { id: "r-12", userId: "u-7", targetType: "event", targetId: "evt-2", axisKeys: ["wantToOwn", "moved"], writtenTakeTH: "อยากได้ภาพที่สองจากซ้ายในห้องแรกมาก ไม่รู้ราคาจะหักหัวใจขนาดไหน", attendanceVerified: true, createdAt: "2026-05-23T15:00:00Z" },
  { id: "r-13", userId: "u-8", targetType: "event", targetId: "evt-2", axisKeys: ["confused", "cantStopThinking"], writtenTakeEN: "I don't know if I love or hate it. Three days later I'm still in this show.", attendanceVerified: true, createdAt: "2026-05-22T20:00:00Z" },

  // Margin Notes (evt-3)
  { id: "r-14", userId: "u-2", targetType: "event", targetId: "evt-3", axisKeys: ["moved", "changedMyMind"], writtenTakeEN: "Narawit's series on the Burmese workers in the fishing industry is the best documentary photography I've seen in this city in five years.", attendanceVerified: true, createdAt: "2026-05-17T11:00:00Z" },
  { id: "r-15", userId: "u-4", targetType: "event", targetId: "evt-3", axisKeys: ["moved", "underrated"], writtenTakeEN: "Not enough people talking about this. The Warehouse 30 location almost works against it — too many people going for the aesthetic, missing the work.", attendanceVerified: true, createdAt: "2026-05-16T16:00:00Z" },
  { id: "r-16", userId: "u-6", targetType: "event", targetId: "evt-3", axisKeys: ["moved", "cantStopThinking", "changedMyMind"], attendanceVerified: true, createdAt: "2026-05-18T09:00:00Z" },
  { id: "r-17", userId: "u-8", targetType: "event", targetId: "evt-3", axisKeys: ["underrated"], writtenTakeEN: "This should be in a major institution, not a repurposed warehouse. Which is a compliment and a criticism simultaneously.", attendanceVerified: true, createdAt: "2026-05-20T14:00:00Z" },

  // NEON SAMSARA (evt-7) — classic Instagram bait debate
  { id: "r-18", userId: "u-1", targetType: "event", targetId: "evt-7", axisKeys: ["overhyped", "confused"], writtenTakeTH: "ถ่ายรูปสวย แต่พอนั่งคิดว่ามันพูดถึงอะไร คำตอบคือ: ไม่รู้", attendanceVerified: true, createdAt: "2026-05-03T15:00:00Z" },
  { id: "r-19", userId: "u-3", targetType: "event", targetId: "evt-7", axisKeys: ["wantToOwn", "moved"], writtenTakeTH: "ห้องสีชมพูสุดท้ายมันทำให้ร้องไห้จริงๆ ไม่ว่าจะถ่ายได้ดีไหน", attendanceVerified: true, createdAt: "2026-05-04T16:00:00Z" },
  { id: "r-20", userId: "u-4", targetType: "event", targetId: "evt-7", axisKeys: ["overhyped"], writtenTakeEN: "Beautiful surfaces, vacant centre. The tech is the art, and the art doesn't know that.", attendanceVerified: true, createdAt: "2026-05-02T12:00:00Z" },
  { id: "r-21", userId: "u-5", targetType: "event", targetId: "evt-7", axisKeys: ["moved", "cantStopThinking"], writtenTakeTH: "ฉันไม่แคร์ว่านักวิจารณ์จะพูดอะไร ห้องนั้นทำให้ฉันรู้สึกอยู่นานมาก", attendanceVerified: true, createdAt: "2026-05-05T18:00:00Z" },
  { id: "r-22", userId: "u-8", targetType: "event", targetId: "evt-7", axisKeys: ["overhyped", "confused"], writtenTakeEN: "Six hundred baht to feel like I'm inside a screensaver. The queues outside were longer than my attention inside.", attendanceVerified: true, createdAt: "2026-05-03T19:00:00Z" },
  { id: "r-23", userId: "u-6", targetType: "event", targetId: "evt-7", axisKeys: ["moved"], attendanceVerified: false, createdAt: "2026-05-06T10:00:00Z" },

  // The Committee (evt-15) — political
  { id: "r-24", userId: "u-4", targetType: "event", targetId: "evt-15", axisKeys: ["changedMyMind", "cantStopThinking"], writtenTakeEN: "The rejection letter display is the masterpiece. Forty years of institutional refusals, anonymized. Reading them is devastating.", attendanceVerified: true, createdAt: "2026-05-31T14:00:00Z" },
  { id: "r-25", userId: "u-8", targetType: "event", targetId: "evt-15", axisKeys: ["changedMyMind", "moved"], writtenTakeEN: "I came as a former gallerist. I left wanting to apologise to every artist I ever rejected.", attendanceVerified: true, createdAt: "2026-05-31T16:00:00Z" },
  { id: "r-26", userId: "u-1", targetType: "event", targetId: "evt-15", axisKeys: ["cantStopThinking", "underrated"], writtenTakeTH: "ควรจะมีคนมาดูเยอะกว่านี้ เป็นงานที่พูดถึงทุกคนที่เคยทำศิลปะแล้วถูกปฏิเสธ", attendanceVerified: true, createdAt: "2026-06-01T10:00:00Z" },

  // Soft Hours (evt-13) — strong emotional consensus
  { id: "r-27", userId: "u-7", targetType: "event", targetId: "evt-13", axisKeys: ["moved", "cantStopThinking", "wantToOwn"], writtenTakeTH: "ผ้าที่เธอใช้มันเป็นผ้าของยาย ฉันรู้ทันทีถึงแม้ว่าไม่ใช่ผ้าของยายฉัน", attendanceVerified: true, createdAt: "2026-05-24T15:00:00Z" },
  { id: "r-28", userId: "u-3", targetType: "event", targetId: "evt-13", axisKeys: ["moved", "confused"], writtenTakeTH: "ร้องไห้จริงๆ ไม่รู้ว่าทำไม ดีหรือเปล่าก็ยังไม่แน่ใจ", attendanceVerified: true, createdAt: "2026-05-25T12:00:00Z" },
  { id: "r-29", userId: "u-2", targetType: "event", targetId: "evt-13", axisKeys: ["underrated", "moved"], writtenTakeEN: "Nobody's talking about this. Everybody should be talking about this.", attendanceVerified: true, createdAt: "2026-05-26T11:00:00Z" },
  { id: "r-30", userId: "u-5", targetType: "event", targetId: "evt-13", axisKeys: ["moved"], attendanceVerified: false, createdAt: "2026-05-27T09:00:00Z" },

  // Same Pot, Different Spoon (evt-5)
  { id: "r-31", userId: "u-7", targetType: "event", targetId: "evt-5", axisKeys: ["moved", "wantToOwn", "changedMyMind"], writtenTakeTH: "หม้อหนึ่งใบสามารถบอกเล่าประวัติศาสตร์ครอบครัวได้ทั้งหมด ฉันไม่คิดว่าจะคิดแบบนี้มาก่อน", attendanceVerified: true, createdAt: "2026-05-05T13:00:00Z" },
  { id: "r-32", userId: "u-8", targetType: "event", targetId: "evt-5", axisKeys: ["underrated", "wantToOwn"], writtenTakeEN: "The quietest show at BACC this season. The one you'll remember.", attendanceVerified: true, createdAt: "2026-05-06T14:00:00Z" },
  { id: "r-33", userId: "u-1", targetType: "event", targetId: "evt-5", axisKeys: ["confused"], writtenTakeTH: "ไม่แน่ใจว่างานนำเสนออัตลักษณ์หรือสินค้า บางชิ้นดูเหมือนของที่ระลึก", attendanceVerified: false, createdAt: "2026-05-07T10:00:00Z" },

  // Data Skins (evt-11)
  { id: "r-34", userId: "u-4", targetType: "event", targetId: "evt-11", axisKeys: ["cantStopThinking", "confused"], writtenTakeEN: "Gave my biometric data at the door. Saw it turned into a piece of visual art inside. Can't decide if that was profound or just unsettling.", attendanceVerified: true, createdAt: "2026-04-18T11:00:00Z" },
  { id: "r-35", userId: "u-6", targetType: "event", targetId: "evt-11", axisKeys: ["cantStopThinking", "changedMyMind"], writtenTakeEN: "I came expecting tech-bro aesthetics. The piece about skin microbiomes as data stopped me cold.", attendanceVerified: true, createdAt: "2026-04-19T15:00:00Z" },
  { id: "r-36", userId: "u-2", targetType: "event", targetId: "evt-11", axisKeys: ["overhyped", "confused"], writtenTakeEN: "The data collection at the entrance is a stunt. The work doesn't earn it.", attendanceVerified: true, createdAt: "2026-04-20T16:00:00Z" },

  // Unburied (evt-12) — strong consensus
  { id: "r-37", userId: "u-4", targetType: "event", targetId: "evt-12", axisKeys: ["moved", "changedMyMind", "cantStopThinking"], writtenTakeEN: "The 1976 massacre archive room. I had to sit down. History education in this country is a crime.", attendanceVerified: true, createdAt: "2026-05-07T12:00:00Z" },
  { id: "r-38", userId: "u-2", targetType: "event", targetId: "evt-12", axisKeys: ["moved", "changedMyMind"], writtenTakeEN: "How is this show still up. Grateful that it is.", attendanceVerified: true, createdAt: "2026-05-08T10:00:00Z" },
  { id: "r-39", userId: "u-8", targetType: "event", targetId: "evt-12", axisKeys: ["cantStopThinking", "moved", "changedMyMind"], writtenTakeEN: "Required viewing. Not optional. Bring a notebook.", attendanceVerified: true, createdAt: "2026-05-09T14:00:00Z" },
  { id: "r-40", userId: "u-6", targetType: "event", targetId: "evt-12", axisKeys: ["moved", "underrated"], attendanceVerified: true, createdAt: "2026-05-10T09:00:00Z" },
];
